### PR TITLE
add text and links to ILL and BBM info pages to franklin catalog tab …

### PR DESCRIPTION
**Pull request by mksndz**
…home text.

### CODE REVIEW

**Comment by tampakis** [comment]
I like the use of the config yml to keep track of the urls. Let's link out to [Pickup @ Penn](https://guides.library.upenn.edu/circulation/PickUpatPenn) instead of ILL on this page.

**Comment by mksndz** [comment]
Thanks for the clarification @tampakis . I've updated the link here.

**Comment by tampakis** [comment]
Sorry for providing the incorrect formatting, but I just saw that the pick up service should by formatted as `PickUp@Penn`

**Comment by mksndz** [comment]
No problem. I've taken this opportunity to update the PickUp@Penn labels throughout the site

**Review by tampakis — APPROVED** [review]
Looks great!

**Pull request merged**
